name: Keep Supabase Alive
on:
  schedule:
    - cron: '0 0 */5 * *'  # cada 5 días
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send keep-alive request
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: curl -sSL "$SUPABASE_URL" >/dev/null
        